name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 20
    env:
      THEOS: ${{ github.workspace }}/theos
      SDKVERSION: 16.4

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 设置 Theos 环境并安装依赖
    - name: Setup Theos and Install Dependencies
      run: |
        # 克隆并更新 Theos
        git clone --filter=blob:none --depth 1 \
          https://github.com/theos/theos.git $THEOS
        $THEOS/bin/update-theos
        # 输出 THEOS 目录结构来检查是否正确设置
        ls -la $THEOS
        # 安装 Xcode 命令行工具（如果未安装）
        xcode-select --install || echo "xcode-select already installed"
        # 显示 xcode-select 安装的工具版本
        xcode-select -v
        # 显示当前的 SDK 和开发环境版本
        sw_vers
        # 确保可以使用 xcodebuild
        xcodebuild -version

        # 安装 ldid 工具
        brew install ldid || echo "ldid is already installed"

    # 构建 .deb 包
    - name: Build Tweak Package
      run: |
        export PATH="$THEOS/bin:$PATH"
        make clean
        make package \
          THEOS_PACKAGE_SCHEME=rootless \
          DEBUG=0 \
          CODESIGNING_ALLOWED=NO

    # 上传构建的 .deb 包
    - name: Upload .deb Artifact
      uses: actions/upload-artifact@v4
      with:
        name: 全局水印_${{ github.run_number }}
        path: packages/*.deb
