name: CI

# 仅当 build.yml 文件发生变化时触发工作流
on:
  push:
    paths:
      - '.github/workflows/build.yml'  # 监控 build.yml 文件的变化
      - 'Tweak.x'  # 增加对 Tweak.xm 文件的监控
      - 'control' 
    branches:
      - 'main'  # 仅在推送到 main 分支时触发
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Theos Setup Action
        uses: axs66/theos-action@main

      - name: Setup Theos SDK
        run: |
          mkdir -p $HOME/theos/sdks
          cd $HOME/theos/sdks
          wget https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz
          tar -xf iPhoneOS14.5.sdk.tar.xz


      - name: Clean previous packages
        run: rm -f ${{ github.workspace }}/packages/*.deb

      - name: Build DEB (rootless + roothide)
        run: |
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=root

      - name: List generated DEBs
        run: ls -lh ${{ github.workspace }}/packages

      - name: Create GitHub Release
        run: |
          VERSION=$(date +v%Y%m%d%H%M)
          gh release create $VERSION ${{ github.workspace }}/packages/*.deb --title "全局水印 $VERSION" --notes "自动构建 .deb 安装包"
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: Upload DEB to workflow artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: 全局水印
          path: ${{ github.workspace }}/packages/*.deb
