name: deb

on:
  push:
    paths:
      - '.github/workflows/build.yml'  # 监控 build.yml 文件的变化
      - '**.xm'  # 增加对 Tweak.xm 文件的监控
      - 'control'
    branches:
      - 'main'  # 仅在推送到 main 分支时触发
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Prepare Theos
        uses: axs66/theos-action@main

      - name: Build package
        run: |
          rm -f ${{ github.workspace }}/packages/*.deb
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=root

      - name: List generated Deb packages
        run: ls ${{ github.workspace }}/packages

      - name: Create GitHub Release
        id: release
        run: |
          VERSION=$(date +v%Y%m%d%H%M)
          gh release create $VERSION ${{ github.workspace }}/packages/*.deb --title "全局水印 $VERSION" --notes "Automated release of .deb files"
        env:
          GH_TOKEN: ${{ secrets.PAT }}  # 这里设置了 GitHub Token 用于授权

      - name: Upload specific Deb packages
        uses: actions/upload-artifact@v4.3.3
        with:
          name: 全局水印
          path: ${{ github.workspace }}/packages/*.deb
